Added IANA headers
denoland/std pull request #4317
Opened 2024-02-12 12:37 UTC by halvardssm

Adds IANA Headers as a follow-up from #4304

2024-08-05 10:25 UTC, iuioiua requested changes
Yoshiya and I would now like to have this addition.

Can you please remove `HttpHeaderDeprecated`, `HttpHeaderObsoleted` and `HttpHeaderProvisional` objects? What's now `HttpHeaderPermanent` seems to be the only object needed for now.

Can you please also add simple/minimal tests to ensure the plumbing works?

2024-08-05 10:25 UTC, iuioiua commented on http/header.ts
> +export type HttpHeader = typeof HttpHeader[keyof typeof HttpHeader];
```suggestion
export type Header = typeof HEADER[keyof typeof HEADER];
```

2024-08-05 10:25 UTC, iuioiua commented on http/header.ts
> +export const HttpHeaderPermanent = {
```suggestion
export const HEADER = {
```

2024-08-05 16:37 UTC, halvardssm commented
@iuioiua Done! Let me know if there is anything else!

2024-08-06 09:29 UTC, iuioiua approved these changes
LGTM! Thank you for this.

2024-08-06 09:29 UTC, merged