feat(encoding) Added base32 hex decode and encode.
denoland/std pull request #4931
Opened 2024-06-02 21:14 UTC by BenMcLean981

As requested in #4917 I have added base32hex encoding and decoding.

I first created new tests from the base32 test cases and using this tool:
https://tomeko.net/online_tools/base32hex.php?lang=en

Once those tests passed, I extracted the common base32 and base32 hex into a `_utils`module with a new parameter for a lookup table.

This is my first time contributing to an open source project and using deno. I am having trouble running the `task ok`. It is failing on my documentation examples with the error below. I think I'm missing a step though, because it's executing with the published module from jsr rather than the local version. This means it makes sense that my module is not there, because it won't be in version 0.224.3. If there's any step I'm missing here I'd really appreciate any feedback.

```
[error] Failed to execute snippet: 
import { decodeBase32Hex } from "@std/encoding/base32hex";
import { assertEquals } from "@std/assert/assert-equals";

assertEquals(
  decodeBase32Hex("GZRTMMDDGA======"),
  new TextEncoder().encode("6c60c0"),
);
error: Unknown export './base32hex' for '@std/encoding@0.224.3'.
  Package exports:
 * .
 * ./ascii85
 * ./base32
 * ./base58
 * ./base64
 * ./base64url
 * ./hex
 * ./varint
 at file:///home/benmclean/projects/deno/deno_std/encoding/base32hex.ts:54
[error] Failed to execute snippet: 
import { encodeBase32Hex } from "@std/encoding/base32hex";
import { assertEquals } from "@std/assert/assert-equals";

assertEquals(encodeBase32Hex("6c60c0"), "GZRTMMDDGA======");
error: Unknown export './base32hex' for '@std/encoding@0.224.3'.
  Package exports:
 * .
 * ./ascii85
 * ./base32
 * ./base58
 * ./base64
 * ./base64url
 * ./hex
 * ./varint
 at file:///home/benmclean/projects/deno/deno_std/encoding/base32hex.ts:74
2 errors found
```

2024-06-02 21:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno_std?pullRequest=4931) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno_std?pullRequest=4931) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno_std?pullRequest=4931) it.</sub>

2024-06-03 00:17 UTC, iuioiua reviewed
Thank you for this. `@std/encoding is about to be in its release candidate phase, so it'll be in a change freeze (except for documentation improvements and bug fixes). This change will be merged once that's complete.

2024-06-03 00:17 UTC, iuioiua commented on assert/assert_almost_equals.ts
> +  const f = (n: number) => (Number.isInteger(n) ? n : n.toExponential());
Please revert this. This is unrelated to the objective of this PR.

2024-06-05 22:23 UTC, iuioiua requested changes
Can you please add the new module to the exports in `encoding/deno.json`?

2024-06-06 10:59 UTC, BenMcLean981 commented
> Can you please add the new module to the exports in `encoding/deno.json`?

I actually already did, I didn't add the `_utils.ts` module though because it should be private.

2024-06-07 04:04 UTC, BlackAsLight commented
The only error left seems to be that you forgot to update the assertEquals in the jsdoc examples when you copied it over.

2024-06-07 10:49 UTC, BenMcLean981 commented
> The only error left seems to be that you forgot to update the assertEquals in the jsdoc examples when you copied it over.

Good catch, this has been fixed, thanks.

2024-08-01 02:56 UTC, iuioiua commented
Hey there. Sorry for the delay. On second thought, with the only difference being the alphabet used, I think we should add an `options` argument to the base32 functions, instead of creating new symbols and modules. It could look like this.
```ts
interface Base32Options {
  /**
   * Base32 format to use.
   *
   * @default {"standard"}
   */
  format?: "standard" | "hex";
}
```
What do y'all think?

2024-08-01 03:23 UTC, iuioiua commented
Actually, we can have separate functions but have them all in the existing `base32` module, since there's so much overlap.

2024-08-01 05:15 UTC, BlackAsLight commented
I think the best way to do it would be the same way base64 and base64url are done.

2024-08-01 05:18 UTC, iuioiua commented
base32 and base32Hex functions have almost complete overlap - there's no benefit to separating them. Arguably, the same could be said for base32Url, but that's a separate conversation.

2024-08-01 08:34 UTC, BlackAsLight commented
I don't have an opinion one way or the other on how it should be done, but I think consistency is best.

2024-08-09 09:56 UTC, iuioiua approved these changes
I chatted with Yoshiya, and on second thought, we're happy to proceed with this format. I also made a couple of tweaks. Now, LGTM! Thank you very much.

2024-08-09 09:57 UTC, merged