fix(expect): export missing `ExtendMatchResult` type
denoland/std pull request #5309
Opened 2024-07-04 18:24 UTC by lowlighter

Looking at how you need to use `expect.extend`, the return type `ExtendMatchResult` is expected but it is not exported publicly:
https://github.com/denoland/deno_std/blob/81943c34c7ba662ee44446d4fa49790e7138ee23/expect/_extend_test.ts#L7-L11

Workaround is to use `any` but it's not ideal
```ts
declare module "@std/expect" {
  interface Expected {
    toMatchDescriptor: (key: PropertyKey, expected:PropertyDescriptor) => any;
  }
}

2024-07-04 22:58 UTC, iuioiua requested changes
It seems we need to export more of the underlying types, like `MatchResult`, `ExtendMatchResult`, `MatcherContext`, etc.

Also, it seems this PR targets this TODO:
https://github.com/denoland/deno_std/blob/a92e1b6060347bbf9f4c39aeb3120adb812f4c7e/expect/expect.ts#L290

2024-07-05 03:41 UTC, lowlighter commented
@iuioiua 
Yeah I noticed with the errors of the ci, there's a lot more to export but I'm not so sure what's the best anymore

It feels weird to export so many types which aren't necessarly "needed", because TS seems to be able to infer a lot of stuff.
Also turns out that passing `unknown` as return type is acceptable and doesn't really affects the code despite being a bit "less precise":

```ts
declare module "@std/expect" {
  interface Expected {
    toMatchDescriptor: (key: PropertyKey, expected:PropertyDescriptor) => unknown;
  }
}

expect(Object.defineProperties({}, {foo:{value:"bar", writable:false}}))
  .toMatchDescriptor("foo", {writable:false}) // no typing issue nor runtime errors
```

So tbh I'm not sure this is worth implementing, thoughts ?

2024-07-05 03:43 UTC, iuioiua commented
Any preferences, @kt3k?

2024-07-05 03:44 UTC, lowlighter commented
I'm not sure whether the way I did it is the "official way" to do it since https://jsr.io/@std/expect/doc/~/expect.extend is currently undocumented (I looked up the unit test and wasn't even aware such a thing existed previously)

But if that's seem the intended way, maybe I could change the scope of this PR to document `expect.extend` instead ?

2024-07-05 03:56 UTC, kt3k commented
> But if that's seem the intended way, maybe I could change the scope of this PR to document expect.extend instead ?

Sounds great!

2024-07-05 06:36 UTC, lowlighter commented
Hum, there's a small catch though

Extending `Expected` interface based on how it's done in the unit test render the package unpublishable on jsr.io :
```bash
error[unsupported-ambient-module]: found an ambient module, which is a global augmentation, which are not unsupported
 --> C:\...\libs\testing\_expect.ts:8:16
  |
8 | declare module "@std/expect" {
  |                ^^^^^^^^^^^^^
  = hint: remove the ambient module declaration

  info: ambient modules are not supported because they can modify the types of a module from outside of that module
  docs: https://jsr.io/go/slow-type-unsupported-ambient-module
```

I think maybe it can be worked around by changing the signature of `expect():Expected` to `expect<T extends Expected = Expected>():T` so it's possible to extends the interface instead ? (Not sure if it works though, not tested)

2024-07-07 01:59 UTC, lowlighter commented
@kt3k @iuioiua 

After experimenting a bit for [`@libs/testing/expect`](https://jsr.io/@libs/testing/2.1.0/expect.ts#L18), it seems like the workaround suggested to just make the `expect` generic to accept and extended `Extended` interface works good enough.

There's no need to export additional typings it seems (just using unknown as return type is fine), however there's still the fact you need to manually override the `not`/`resolves`/`rejects` since it's not possible to create interface with recursive type parameters.
```ts
interface ExtendedExpected<IsAsync = false> extends Expected<IsAsync> {
  not: IsAsync extends true ? Async<ExtendedExpected<true>> : ExtendedExpected<false>;
  resolves: Async<ExtendedExpected<true>>;
  rejects: Async<ExtendedExpected<true>>;
}
```

I've put together an exhaustive example of what I've gathered while using `expect.extend` and changed the scope of this PR to reflect more what's the intended goal

2024-07-14 00:17 UTC, iuioiua commented
PTAL @kt3k

2024-07-16 04:01 UTC, kt3k commented on expect/_extend_test.ts
> +  await myexpect(Promise.resolve("🦧")).resolves.not.toBeDinosaur();
Confirmed these are correctly type checked in `deno test` and in the editor. Nice work!

<img width="864" alt="Screenshot 2024-07-16 at 12 59 46" src="https://github.com/user-attachments/assets/0239ae54-bc56-4321-b8a9-094cccd24c59">

2024-07-16 04:02 UTC, kt3k approved these changes
LGTM

2024-07-16 04:09 UTC, merged