refactor(front_matter): replace regexp factory with regexp literals
denoland/std pull request #5370
Opened 2024-07-09 12:53 UTC by timreichen

- replaces `createRegExps` with regexp literals

2024-07-09 12:56 UTC, kt3k commented
This looks harder to maintain to me.

2024-07-09 21:35 UTC, timreichen commented
I think the building step is more complex and harder to understand than simple regexes, as they are very straight forward. If you'd like I could add names to capturing groups.

2024-07-09 23:49 UTC, iuioiua approved these changes
While I wouldn't call the `EXTRACT_*` constants "simple regexes", this is simpler and easier to understand to me, compared to regex factories.

2024-07-09 23:49 UTC, iuioiua commented on front_matter/_formats.ts
> +export const EXTRACT_REGEXP_MAP: Record<Format, RegExp> = {
Sidenote: we should change these to `Map`s.

2024-07-10 01:37 UTC, kt3k commented
Repetition of the same pattern (such as `---toml|\+\+\+|= toml =`) in multiple places doesn't look great to me. It feels like a error-prone.

2024-07-10 03:34 UTC, kt3k commented on front_matter/_formats.ts
> +const RECOGNIZE_YAML_REGEXP = /^---yaml|= yaml =|---$/im;
I think these regexes need parens.
```suggestion
const RECOGNIZE_YAML_REGEXP = /^(?:---yaml|= yaml =|---)$/im;
```

2024-07-10 07:35 UTC, timreichen commented
> Repetition of the same pattern (such as `---toml|\+\+\+|= toml =`) in multiple places doesn't look great to me. It feels like a error-prone.

I think the repetition is justified because they are two different regexps, one for recognizing and one for extracting.

Btw, I think the extract regexes could be written without the multiline flag:

```ts
const EXTRACT_YAML_REGEXP =
  /^\ufeff?(?:---yaml|= yaml =|---)([\s\S]+?\r?\n)(?:---|= yaml =)\s*\r?\n?/i;
const EXTRACT_TOML_REGEXP =
  /^\ufeff?(?:---toml|\+\+\+|= toml =)([\s\S]+?\r?\n)(?:---|\+\+\+|= toml =)\s*\r?\n?/i;
const EXTRACT_JSON_REGEXP =
  /^\ufeff?(?:---json|= json =)([\s\S]+?\r?\n)(?:---|= json =)\s*\r?\n?/i;
  ```

2024-07-10 08:30 UTC, kt3k commented
> I think the repetition is justified because they are two different regexps, one for recognizing and one for extracting.

I don't understand this reasoning. Why is it justified because of 2 regexps? Current code reuses the same pattern for 2 regexps. Isn't that an ideal state?

> `/^\ufeff?(?:---yaml|= yaml =|---)([\s\S]+?\r?\n)(?:---|= yaml =)\s*\r?\n?/i;`

This example has error in closing part. Feels like proving it's an error-prone.

2024-07-11 10:27 UTC, timreichen commented
Ok, what about creating the regexps with string literals like we do in semver?

2024-07-11 22:27 UTC, iuioiua commented
> Ok, what about creating the regexps with string literals like we do in semver?

Let's try that.

2024-07-22 01:36 UTC, iuioiua requested changes
I've added a temporary test (for the lifetime of this PR) that is a proof that the old constants are equivalent to the new ones. It's currently failing. Please ensure this test passes.

2024-07-31 23:19 UTC, iuioiua approved these changes
LGTM, as these constants seem easier to follow, compared to the previous functions, and have been shown to be equivalent in https://github.com/denoland/std/pull/5370/commits/11b5f3edc8668917a5ccb8c2e2ae3f848340939e.

@timreichen, frankly, we'll be reluctant to accept any further simplifications to these regexes. Getting regexes are hard, and can very subtle mistakes can lead to bugs. Nevertheless, we can take a look at a PR, but no guarentees in it being merged.

Either way, thank you.

2024-07-31 23:19 UTC, merged