refactor(yaml): cleanup `stringifyFlowMapping()`
denoland/std pull request #5743
Opened 2024-08-20 09:02 UTC by timreichen

2024-08-22 02:58 UTC, iuioiua reviewed
This method is not yet fully tested. I'd only feel completely comfortable merging this PR once it's fully tested. See https://app.codecov.io/gh/denoland/std/blob/main/yaml%2F_dumper_state.ts#L627

2024-08-22 07:55 UTC, iuioiua requested changes
Frankly, I don't really see the purpose behind this PR.

2024-08-22 07:55 UTC, iuioiua commented on yaml/_dumper_state.ts
>        pairBuffer += valueString;
Can be done in one line.

2024-08-22 08:02 UTC, timreichen commented
> Frankly, I don't really see the purpose behind this PR.

There are several (tiny) performance benefits:
- `quote` and `separator` are take out of the loop, therefore only need one check
- `stringifyNode()`for key and value is called at the beginning of the loop, thus continues the loop before `pairBuffer` is even initialized.

It also is more readable imo.

2024-08-26 02:13 UTC, iuioiua approved these changes
Thank you

2024-08-26 02:13 UTC, merged