docs(async): add note about deadline DOMException name of TimeoutError
denoland/std pull request #5833
Opened 2024-08-26 12:33 UTC by lionel-rowe

Towards https://github.com/denoland/std/issues/5679

2024-08-26 23:18 UTC, iuioiua requested changes

2024-08-26 23:18 UTC, iuioiua commented on async/deadline.ts
> + * `name` property will be set to `"TimeoutError"`.
It'd also be great if we mentioned when `AbortError` is thrown.

2024-08-27 14:49 UTC, kt3k approved these changes
LGTM

2024-08-28 05:46 UTC, iuioiua approved these changes
LGTM. Thanks!

Note to self: check this once `@throws` rendering is fixed in `deno doc` (see https://github.com/denoland/deno_doc/issues/299).

2024-08-28 05:46 UTC, merged